---
- hosts: vm-1
  become: yes
  tasks:

  - name: install apache2
    ansible.builtin.apt:
      name: apache2
      state: latest
      update_cache: yes
    when: ansible_facts ['distribution'] == "Ubuntu"

  - name: changing index.html via jinja2 template
    template:
      src: index.html.j2
      dest: /var/www/html/index.html

  - name: Check that webserver is reachable and has status 200
    ansible.builtin.uri:
      url: http://84.201.167.209:80